version: '3.5'

services:
  db:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: recipehub
    ports:
      - 5432:5432
    restart: always
    container_name: recipehub_postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
     nuxt-network:
  redis:
    image: redis
    ports:
      - 6379:6379
    restart: always
    container_name: recipehub_redis
    command: redis-server --requirepass redis --save 20 1 --loglevel warning
    volumes:
      - redis:/data
    networks:
     nuxt-network:
  app:
    build: ./backend
    container_name: recipehub_backend
    ports:
      - 3000:3000
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend:/app
    networks:
      - nuxt-network
  frontend:
    build: ./frontend
    container_name: recipehub_frontend
    ports:
      - 8080:8080
    depends_on:
      - app
    networks:
      - nuxt-network
  web-server:
    build: ./proxy
    container_name: recipehub_proxy
    ports:
      - 80:80
    networks:
      nuxt-network:
    depends_on:
      - frontend
    restart: unless-stopped
volumes:
  pgdata:
  redis:
  web-root:
networks:
  nuxt-network:
    driver: bridge
